#!/bin/bash

set -e

WOWDIR="$HOME/.wow"
mkdir -p "$WOWDIR"
ln -sf /opt/wotlk3.3.5a/{*.dll,*.exe,Data} "$WOWDIR"
test -d "$WOWDIR/WTF" || cp -TR /opt/wotlk3.3.5a/WTF "$WOWDIR/WTF"
WINEDLLOVERRIDES="mscoree,mshtml=" wine "$WOWDIR/Wow.exe"
